

  const currentMonth = new Date().getMonth() + 1
  const currentYear = new Date().getFullYear();
  String(currentMonth)
  String(currentYear)
  console.log('currentMonth',currentMonth);
  console.log('currentYear',currentYear);
  




const flightDetails =  [
  {
    "flight_number": "PK301",
    "airline": "Airblue",
    "image": "https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
    "from_to": "Karachi - Lahore",
    "departure_airport": "Karachi Jinnah International Airport",
    "arrival_airport": "Lahore Allama Iqbal International Airport",
    "departure_date": `${currentYear}-${currentMonth}-15`,
    "departure_time": "08:00",
    "arrival_date": `${currentYear}-${currentMonth}-15`,
    "arrival_time": "09:30",
    "flight_duration_hours": 1.5,
    "price": 8000,
    "ticket_class": "Economy",
    "review": 4.2,
    "cheapest": true,
    "best": false,
    "quickest": false,
    "type": "one-way"
  },
  {
    "flight_number": "PK302",
    "airline": "Pakistan International Airlines",
    "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
    "from_to": "Lahore - Karachi",
    "departure_airport": "Lahore Allama Iqbal International Airport",
    "arrival_airport": "Karachi Jinnah International Airport",
    "departure_date": `${currentYear}-${currentMonth}-15`,
    "departure_time": "10:30",
    "arrival_date": `${currentYear}-${currentMonth}-15`,
    "arrival_time": "12:00",
    "flight_duration_hours": 1.5,
    "price": 9500,
    "ticket_class": "Business",
    "review": 4.5,
    "cheapest": false,
    "best": true,
    "quickest": false,
    "type": "return",
    "return": {
      "return_departure_airport": "Karachi Jinnah International Airport",
      "return_arrival_airport": "Lahore Allama Iqbal International Airport",
      "return_departure_date": `${currentYear}-${currentMonth}-18`,
      "return_departure_time": "16:00",
      "return_arrival_date": `${currentYear}-${currentMonth}-18`,
      "return_arrival_time": "17:30"
    }
  },
  {
    "flight_number": "PK303",
    "airline": "Serene Air",
    "image": "https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
    "from_to": "Islamabad - Lahore",
    "departure_airport": "Islamabad International Airport",
    "arrival_airport": "Lahore Allama Iqbal International Airport",
    "departure_date": `${currentYear}-${currentMonth}-15`,
    "departure_time": "14:00",
    "arrival_date": `${currentYear}-${currentMonth}-15`,
    "arrival_time": "15:30",
    "flight_duration_hours": 1.5,
    "price": 9000,
    "ticket_class": "Economy",
    "review": 4.1,
    "cheapest": true,
    "best": false,
    "quickest": true,
    "type": "one-way"
  },
  {
    "flight_number": "PK304",
    "airline": "Airblue",
    "image": "https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
    "from_to": "Karachi - Multan",
    "departure_airport": "Karachi Jinnah International Airport",
    "arrival_airport": "Multan International Airport",
    "departure_date": `${currentYear}-${currentMonth}-16`,
    "departure_time": "09:00",
    "arrival_date": `${currentYear}-${currentMonth}-16`,
    "arrival_time": "10:30",
    "flight_duration_hours": 1.5,
    "price": 7500,
    "ticket_class": "Economy",
    "review": 4.3,
    "cheapest": false,
    "best": false,
    "quickest": false,
    "type": "one-way"
  },
  {
    "flight_number": "PK305",
    "airline": "Pakistan International Airlines",
    "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
    "from_to": "Lahore - Islamabad",
    "departure_airport": "Lahore Allama Iqbal International Airport",
    "arrival_airport": "Islamabad International Airport",
    "departure_date": `${currentYear}-${currentMonth}-16`,
    "departure_time": "15:00",
    "arrival_date": `${currentYear}-${currentMonth}-16`,
    "arrival_time": "16:30",
    "flight_duration_hours": 1.5,
    "price": 8500,
    "ticket_class": "Business",
    "review": 4.7,
    "cheapest": false,
    "best": true,
    "quickest": false,
    "type": "return",
    "return": {
      "return_departure_airport": "Islamabad International Airport",
      "return_arrival_airport": "Lahore Allama Iqbal International Airport",
      "return_departure_date": `${currentYear}-${currentMonth}-16`,
      "return_departure_time": "18:00",
      "return_arrival_date": `${currentYear}-${currentMonth}-16`,
      "return_arrival_time": "19:30"
    }
  },
    {
      "flight_number": "PK306",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Karachi - Islamabad",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": `${currentYear}-${currentMonth}-16`,
      "departure_time": "20:00",
      "arrival_date": `${currentYear}-${currentMonth}-16`,
      "arrival_time": "22:00",
      "flight_duration_hours": 2,
      "price": 11000,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": false,
      "best": false,
      "quickest": true,
      "type": "one-way"
    },
    {
      "flight_number": "PK307",
      "airline": "Airblue",
      "image": "https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Islamabad - Karachi",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": `${currentYear}-${currentMonth}-17`,
      "departure_time": "10:30",
      "arrival_date": `${currentYear}-${currentMonth}-17`,
      "arrival_time": "12:00",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Business",
      "review": 4.6,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Karachi Jinnah International Airport",
        "return_arrival_airport": "Islamabad International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-19`,
        "return_departure_time": "16:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-19`,
        "return_arrival_time": "17:30"
      }
    },
    {
      "flight_number": "PK308",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Peshawar",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Peshawar International Airport",
      "departure_date": `${currentYear}-${currentMonth}-18`,
      "departure_time": "14:00",
      "arrival_date": `${currentYear}-${currentMonth}-18`,
      "arrival_time": "15:30",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Economy",
      "review": 4.2,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK309",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Karachi - Quetta",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Quetta International Airport",
      "departure_date": `${currentYear}-${currentMonth}-18`,
      "departure_time": "18:00",
      "arrival_date": `${currentYear}-${currentMonth}-18`,
      "arrival_time": "19:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.5,
      "cheapest": false,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK310",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Lahore - Karachi",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": `${currentYear}-${currentMonth}-19`,
      "departure_time": "09:30",
      "arrival_date": `${currentYear}-${currentMonth}-19`,
      "arrival_time": "11:00",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.1,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK311",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Karachi - Lahore",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Lahore Allama Iqbal International Airport",
      "departure_date": `${currentYear}-${currentMonth}-20`,
      "departure_time": "12:00",
      "arrival_date": `${currentYear}-${currentMonth}-20`,
      "arrival_time": "13:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.3,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Lahore Allama Iqbal International Airport",
        "return_arrival_airport": "Karachi Jinnah International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-21`,
        "return_departure_time": "14:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-21`,
        "return_arrival_time": "15:30"
      }
    },,
    {
      "flight_number": "PK312",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Islamabad - Quetta",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Quetta International Airport",
      "departure_date": `${currentYear}-${currentMonth}-19`,
      "departure_time": "18:30",
      "arrival_date": `${currentYear}-${currentMonth}-19`,
      "arrival_time": "20:00",
      "flight_duration_hours": 1.5,
      "price": 11000,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": false,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK313",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Karachi - Islamabad",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": `${currentYear}-${currentMonth}-20`,
      "departure_time": "08:00",
      "arrival_date": `${currentYear}-${currentMonth}-20`,
      "arrival_time": "09:30",
      "flight_duration_hours": 1.5,
      "price": 7500,
      "ticket_class": "Economy",
      "review": 4.5,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK314",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Islamabad",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": `${currentYear}-${currentMonth}-20`,
      "departure_time": "12:30",
      "arrival_date": `${currentYear}-${currentMonth}-20`,
      "arrival_time": "14:00",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Business",
      "review": 4.6,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Islamabad International Airport",
        "return_arrival_airport": "Lahore Allama Iqbal International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-22`,
        "return_departure_time": "16:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-22`,
        "return_arrival_time": "17:30"
      }
    },
    {
      "flight_number": "PK315",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Karachi - Peshawar",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Peshawar International Airport",
      "departure_date": `${currentYear}-${currentMonth}-20`,
      "departure_time": "19:00",
      "arrival_date": `${currentYear}-${currentMonth}-20`,
      "arrival_time": "20:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Economy",
      "review": 4.3,
      "cheapest": false,
      "best": false,
      "quickest": true,
      "type": "one-way"
    },
    {
      "flight_number": "PK316",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Islamabad - Karachi",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": `${currentYear}-${currentMonth}-21`,
      "departure_time": "10:00",
      "arrival_date": `${currentYear}-${currentMonth}-21`,
      "arrival_time": "11:30",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK317",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Quetta",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Quetta International Airport",
      "departure_date": `${currentYear}-${currentMonth}-21`,
      "departure_time": "14:00",
      "arrival_date": `${currentYear}-${currentMonth}-21`,
      "arrival_time": "15:30",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Business",
      "review": 4.5,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Quetta International Airport",
        "return_arrival_airport": "Lahore Allama Iqbal International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-23`,
        "return_departure_time": "16:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-23`,
        "return_arrival_time": "17:30"
      }
    },
    {
      "flight_number": "PK318",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Karachi - Lahore",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Lahore Allama Iqbal International Airport",
      "departure_date": `${currentYear}-${currentMonth}-21`,
      "departure_time": "20:00",
      "arrival_date": `${currentYear}-${currentMonth}-21`,
      "arrival_time": "21:30",
      "flight_duration_hours": 1.5,
      "price": 7500,
      "ticket_class": "Economy",
      "review": 4.2,
      "cheapest": false,
      "best": false,
      "quickest": true,
      "type": "one-way"
    },
    {
      "flight_number": "PK319",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Islamabad - Peshawar",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Peshawar International Airport",
      "departure_date": `${currentYear}-${currentMonth}-22`,
      "departure_time": "09:30",
      "arrival_date": `${currentYear}-${currentMonth}-22`,
      "arrival_time": "11:00",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Business",
      "review": 4.1,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK320",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Karachi - Multan",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Multan International Airport",
      "departure_date": `${currentYear}-${currentMonth}-22`,
      "departure_time": "15:00",
      "arrival_date": `${currentYear}-${currentMonth}-22`,
      "arrival_time": "16:30",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Multan International Airport",
        "return_arrival_airport": "Karachi Jinnah International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-24`,
        "return_departure_time": "17:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-24`,
        "return_arrival_time": "18:30"
      }
    },
    {
      "flight_number": "PK321",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Lahore - Islamabad",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": `${currentYear}-${currentMonth}-23`,
      "departure_time": "11:00",
      "arrival_date": `${currentYear}-${currentMonth}-23`,
      "arrival_time": "12:30",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.2,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK322",
      "airline": "Airblue",
      "image": "https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Karachi - Peshawar",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Peshawar International Airport",
      "departure_date": `${currentYear}-${currentMonth}-23`,
      "departure_time": "14:00",
      "arrival_date": `${currentYear}-${currentMonth}-23`,
      "arrival_time": "15:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.6,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Peshawar International Airport",
        "return_arrival_airport": "Karachi Jinnah International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-23`,
        "return_departure_time": "16:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-23`,
        "return_arrival_time": "17:30"
      }
    },
    {
      "flight_number": "PK323",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Karachi",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": `${currentYear}-${currentMonth}-24`,
      "departure_time": "08:00",
      "arrival_date": `${currentYear}-${currentMonth}-24`,
      "arrival_time": "09:30",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.3,
      "cheapest": false,
      "best": false,
      "quickest": true,
      "type": "one-way"
    },
    {
      "flight_number": "PK324",
      "airline": "Serene Air",
      "image": "https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Islamabad - Karachi",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": `${currentYear}-${currentMonth}-24`,
      "departure_time": "12:30",
      "arrival_date": `${currentYear}-${currentMonth}-24`,
      "arrival_time": "14:00",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Business",
      "review": 4.5,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Karachi Jinnah International Airport",
        "return_arrival_airport": "Islamabad International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-26`,
        "return_departure_time": "15:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-26`,
        "return_arrival_time": "16:30"
      }
    },
    {
      "flight_number": "PK325",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Karachi - Quetta",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Quetta International Airport",
      "departure_date": `${currentYear}-${currentMonth}-25`,
      "departure_time": "10:00",
      "arrival_date": `${currentYear}-${currentMonth}-25`,
      "arrival_time": "11:30",
      "flight_duration_hours": 1.5,
      "price": 7500,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK326",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Islamabad",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": `${currentYear}-${currentMonth}-25`,
      "departure_time": "15:00",
      "arrival_date": `${currentYear}-${currentMonth}-25`,
      "arrival_time": "16:30",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Business",
      "review": 4.2,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Islamabad International Airport",
        "return_arrival_airport": "Lahore Allama Iqbal International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-27`,
        "return_departure_time": "17:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-27`,
        "return_arrival_time": "18:30"
      }
    },
    {
      "flight_number": "PK327",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Karachi - Lahore",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Lahore Allama Iqbal International Airport",
      "departure_date": `${currentYear}-${currentMonth}-26`,
      "departure_time": "09:30",
      "arrival_date": `${currentYear}-${currentMonth}-26`,
      "arrival_time": "11:00",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.1,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK328",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Karachi",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": `${currentYear}-${currentMonth}-26`,
      "departure_time": "12:00",
      "arrival_date": `${currentYear}-${currentMonth}-26`,
      "arrival_time": "13:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.5,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Karachi Jinnah International Airport",
        "return_arrival_airport": "Lahore Allama Iqbal International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-29`,
        "return_departure_time": "14:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-29`,
        "return_arrival_time": "15:30"
      }
    },
    {
      "flight_number": "PK329",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Islamabad - Peshawar",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Peshawar International Airport",
      "departure_date": `${currentYear}-${currentMonth}-27`,
      "departure_time": "10:00",
      "arrival_date": `${currentYear}-${currentMonth}-27`,
      "arrival_time": "11:30",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Business",
      "review": 4.4,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK330",
      "airline": "Airblue",
      "image": "https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Karachi - Multan",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Multan International Airport",
      "departure_date": `${currentYear}-${currentMonth}-27`,
      "departure_time": "15:00",
      "arrival_date": `${currentYear}-${currentMonth}-27`,
      "arrival_time": "16:30",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Economy",
      "review": 4.3,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Multan International Airport",
        "return_arrival_airport": "Karachi Jinnah International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-29`,
        "return_departure_time": "17:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-29`,
        "return_arrival_time": "18:30"
      }
    },
    {
      "flight_number": "PK331",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Karachi",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": `${currentYear}-${currentMonth}-28`,
      "departure_time": "08:00",
      "arrival_date": `${currentYear}-${currentMonth}-28`,
      "arrival_time": "09:30",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK332",
      "airline": "Airblue",
      "image": "https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Karachi - Islamabad",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": `${currentYear}-${currentMonth}-28`,
      "departure_time": "12:00",
      "arrival_date": `${currentYear}-${currentMonth}-28`,
      "arrival_time": "13:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.6,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Islamabad International Airport",
        "return_arrival_airport": "Karachi Jinnah International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-30`,
        "return_departure_time": "15:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-30`,
        "return_arrival_time": "16:30"
      }
    },
    {
      "flight_number": "PK333",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Islamabad - Lahore",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Lahore Allama Iqbal International Airport",
      "departure_date": `${currentYear}-${currentMonth}-29`,
      "departure_time": "10:00",
      "arrival_date": `${currentYear}-${currentMonth}-29`,
      "arrival_time": "11:30",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Business",
      "review": 4.1,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK334",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Karachi - Peshawar",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Peshawar International Airport",
      "departure_date": `${currentYear}-${currentMonth}-29`,
      "departure_time": "15:00",
      "arrival_date": `${currentYear}-${currentMonth}-29`,
      "arrival_time": "16:30",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Peshawar International Airport",
        "return_arrival_airport": "Karachi Jinnah International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-30`,
        "return_departure_time": "17:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-30`,
        "return_arrival_time": "18:30"
      }
    },
    {
      "flight_number": "PK335",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Lahore - Karachi",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": `${currentYear}-${currentMonth}-30`,
      "departure_time": "09:30",
      "arrival_date": `${currentYear}-${currentMonth}-30`,
      "arrival_time": "11:00",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.3,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK336",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Islamabad - Multan",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Multan International Airport",
      "departure_date": `${currentYear}-${currentMonth}-30`,
      "departure_time": "12:00",
      "arrival_date": `${currentYear}-${currentMonth}-30`,
      "arrival_time": "13:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.6,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Multan International Airport",
        "return_arrival_airport": "Islamabad International Airport",
        "return_departure_date": `${currentYear}-${currentMonth}-30`,
        "return_departure_time": "14:00",
        "return_arrival_date": `${currentYear}-${currentMonth}-30`,
        "return_arrival_time": "15:30"
      }
    },
    {
      "flight_number": "PK337",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Karachi - Lahore",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Lahore Allama Iqbal International Airport",
      "departure_date": "2024-11-1",
      "departure_time": "08:00",
      "arrival_date": "2024-11-1",
      "arrival_time": "09:30",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.2,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK338",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Karachi",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": "2024-11-1",
      "departure_time": "10:30",
      "arrival_date": "2024-11-1",
      "arrival_time": "12:00",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.5,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Karachi Jinnah International Airport",
        "return_arrival_airport": "Lahore Allama Iqbal International Airport",
        "return_departure_date": "2024-11-3",
        "return_departure_time": "13:00",
        "return_arrival_date": "2024-11-3",
        "return_arrival_time": "14:30"
      }
    },
    {
      "flight_number": "PK339",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Islamabad - Lahore",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Lahore Allama Iqbal International Airport",
      "departure_date": "2024-11-1",
      "departure_time": "14:00",
      "arrival_date": "2024-11-1",
      "arrival_time": "15:30",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Economy",
      "review": 4.1,
      "cheapest": true,
      "best": false,
      "quickest": true,
      "type": "one-way"
    },
    {
      "flight_number": "PK340",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Karachi - Multan",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Multan International Airport",
      "departure_date": "2024-11-2",
      "departure_time": "09:00",
      "arrival_date": "2024-11-2",
      "arrival_time": "10:30",
      "flight_duration_hours": 1.5,
      "price": 7500,
      "ticket_class": "Economy",
      "review": 4.3,
      "cheapest": false,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK341",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Islamabad",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": "2024-11-2",
      "departure_time": "15:00",
      "arrival_date": "2024-11-2",
      "arrival_time": "16:30",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Business",
      "review": 4.7,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Islamabad International Airport",
        "return_arrival_airport": "Lahore Allama Iqbal International Airport",
        "return_departure_date": "2024-11-3",
        "return_departure_time": "17:00",
        "return_arrival_date": "2024-11-3",
        "return_arrival_time": "18:30"
      }
    },
    {
      "flight_number": "PK342",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Karachi - Islamabad",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": "2024-11-1",
      "departure_time": "20:00",
      "arrival_date": "2024-11-1",
      "arrival_time": "22:00",
      "flight_duration_hours": 2,
      "price": 11000,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": false,
      "best": false,
      "quickest": true,
      "type": "one-way"
    },
    {
      "flight_number": "PK343",
      "airline": "Airblue",
      "image": "https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Islamabad - Karachi",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": "2024-11-2",
      "departure_time": "10:30",
      "arrival_date": "2024-11-2",
      "arrival_time": "12:00",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Business",
      "review": 4.6,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Karachi Jinnah International Airport",
        "return_arrival_airport": "Islamabad International Airport",
        "return_departure_date": "2024-11-4",
        "return_departure_time": "13:30",
        "return_arrival_date": "2024-11-4",
        "return_arrival_time": "15:00"
      }
    },
    {
      "flight_number": "PK344",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Peshawar",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Peshawar International Airport",
      "departure_date": "2024-11-3",
      "departure_time": "14:00",
      "arrival_date": "2024-11-3",
      "arrival_time": "15:30",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Economy",
      "review": 4.2,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK345",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Karachi - Quetta",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Quetta International Airport",
      "departure_date": "2024-11-3",
      "departure_time": "18:00",
      "arrival_date": "2024-11-3",
      "arrival_time": "19:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.5,
      "cheapest": false,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK346",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Lahore - Karachi",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": "2024-11-4",
      "departure_time": "09:30",
      "arrival_date": "2024-11-4",
      "arrival_time": "11:00",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.1,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK347",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Karachi - Lahore",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Lahore Allama Iqbal International Airport",
      "departure_date": "2024-11-4",
      "departure_time": "12:00",
      "arrival_date": "2024-11-4",
      "arrival_time": "13:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.3,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Lahore Allama Iqbal International Airport",
        "return_arrival_airport": "Karachi Jinnah International Airport",
        "return_departure_date": "2024-11-6",
        "return_departure_time": "14:00",
        "return_arrival_date": "2024-11-6",
        "return_arrival_time": "15:30"
      }
    },
    {
      "flight_number": "PK348",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Islamabad - Quetta",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Quetta International Airport",
      "departure_date": "2024-11-4",
      "departure_time": "18:30",
      "arrival_date": "2024-11-4",
      "arrival_time": "20:00",
      "flight_duration_hours": 1.5,
      "price": 11000,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": false,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK349",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Karachi - Islamabad",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": "2024-11-5",
      "departure_time": "08:00",
      "arrival_date": "2024-11-5",
      "arrival_time": "09:30",
      "flight_duration_hours": 1.5,
      "price": 7500,
      "ticket_class": "Economy",
      "review": 4.5,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK350",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Islamabad",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": "2024-11-5",
      "departure_time": "12:30",
      "arrival_date": "2024-11-5",
      "arrival_time": "14:00",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Business",
      "review": 4.6,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Islamabad International Airport",
        "return_arrival_airport": "Lahore Allama Iqbal International Airport",
        "return_departure_date": "2024-11-7",
        "return_departure_time": "14:00",
        "return_arrival_date": "2024-11-7",
        "return_arrival_time": "15:30"
      }
    },
    {
      "flight_number": "PK351",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Karachi - Peshawar",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Peshawar International Airport",
      "departure_date": "2024-11-5",
      "departure_time": "19:00",
      "arrival_date": "2024-11-5",
      "arrival_time": "20:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Economy",
      "review": 4.3,
      "cheapest": false,
      "best": false,
      "quickest": true,
      "type": "one-way"
    },
    {
      "flight_number": "PK352",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Islamabad - Karachi",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": "2024-11-6",
      "departure_time": "10:00",
      "arrival_date": "2024-11-6",
      "arrival_time": "11:30",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK353",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Quetta",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Quetta International Airport",
      "departure_date": "2024-11-6",
      "departure_time": "14:00",
      "arrival_date": "2024-11-6",
      "arrival_time": "15:30",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Business",
      "review": 4.5,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Quetta International Airport",
        "return_arrival_airport": "Lahore Allama Iqbal International Airport",
        "return_departure_date": "2024-11-8",
        "return_departure_time": "14:00",
        "return_arrival_date": "2024-11-8",
        "return_arrival_time": "15:30"
      }
    },
    {
      "flight_number": "PK354",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Karachi - Lahore",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Lahore Allama Iqbal International Airport",
      "departure_date": "2024-11-6",
      "departure_time": "20:00",
      "arrival_date": "2024-11-6",
      "arrival_time": "21:30",
      "flight_duration_hours": 1.5,
      "price": 7500,
      "ticket_class": "Economy",
      "review": 4.2,
      "cheapest": false,
      "best": false,
      "quickest": true,
      "type": "one-way"
    },
    {
      "flight_number": "PK355",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Islamabad - Peshawar",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Peshawar International Airport",
      "departure_date": "2024-11-7",
      "departure_time": "09:30",
      "arrival_date": "2024-11-7",
      "arrival_time": "11:00",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Business",
      "review": 4.1,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK356",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Karachi - Multan",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Multan International Airport",
      "departure_date": "2024-11-7",
      "departure_time": "15:00",
      "arrival_date": "2024-11-7",
      "arrival_time": "16:30",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Multan International Airport",
        "return_arrival_airport": "Karachi Jinnah International Airport",
        "return_departure_date": "2024-11-9",
        "return_departure_time": "12:00",
        "return_arrival_date": "2024-11-9",
        "return_arrival_time": "14:30"
      }
      
    },
    {
      "flight_number": "PK357",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Lahore - Islamabad",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": "2024-11-8",
      "departure_time": "11:00",
      "arrival_date": "2024-11-8",
      "arrival_time": "12:30",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.2,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK358",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Karachi - Peshawar",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Peshawar International Airport",
      "departure_date": "2024-11-8",
      "departure_time": "14:00",
      "arrival_date": "2024-11-8",
      "arrival_time": "15:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.6,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Peshawar International Airport",
        "return_arrival_airport": "Karachi Jinnah International Airport",
        "return_departure_date": "2024-11-10",
        "return_departure_time": "13:00",
        "return_arrival_date": "2024-11-10",
        "return_arrival_time": "16:30"
      }
    },
    {
      "flight_number": "PK359",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Karachi",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": "2024-11-9",
      "departure_time": "08:00",
      "arrival_date": "2024-11-9",
      "arrival_time": "09:30",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.3,
      "cheapest": false,
      "best": false,
      "quickest": true,
      "type": "one-way"
    },
    {
      "flight_number": "PK360",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Islamabad - Karachi",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": "2024-11-9",
      "departure_time": "12:30",
      "arrival_date": "2024-11-9",
      "arrival_time": "14:00",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Business",
      "review": 4.5,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Karachi Jinnah International Airport",
        "return_arrival_airport": "Islamabad International Airport",
        "return_departure_date": "2024-11-12",
        "return_departure_time": "13:00",
        "return_arrival_date": "2024-11-12",
        "return_arrival_time": "16:30"
      }
    },
    {
      "flight_number": "PK361",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Karachi - Quetta",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Quetta International Airport",
      "departure_date": "2024-11-10",
      "departure_time": "10:00",
      "arrival_date": "2024-11-10",
      "arrival_time": "11:30",
      "flight_duration_hours": 1.5,
      "price": 7500,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK362",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Islamabad",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": "2024-11-10",
      "departure_time": "15:00",
      "arrival_date": "2024-11-10",
      "arrival_time": "16:30",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Business",
      "review": 4.2,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Islamabad International Airport",
        "return_arrival_airport": "Lahore Allama Iqbal International Airport",
        "return_departure_date": "2024-11-13",
        "return_departure_time": "11:00",
        "return_arrival_date": "2024-11-13",
        "return_arrival_time": "12:30"
      }
    },
    {
      "flight_number": "PK363",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Karachi - Lahore",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Lahore Allama Iqbal International Airport",
      "departure_date": "2024-11-11",
      "departure_time": "09:30",
      "arrival_date": "2024-11-11",
      "arrival_time": "11:00",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.1,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK364",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Karachi",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": "2024-11-11",
      "departure_time": "12:00",
      "arrival_date": "2024-11-11",
      "arrival_time": "13:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.5,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Karachi Jinnah International Airport",
        "return_arrival_airport": "Lahore Allama Iqbal International Airport",
        "return_departure_date": "2024-11-15",
        "return_departure_time": "12:00",
        "return_arrival_date": "2024-11-15",
        "return_arrival_time": "13:30"
      }
    },
    {
      "flight_number": "PK365",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Islamabad - Peshawar",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Peshawar International Airport",
      "departure_date": "2024-11-12",
      "departure_time": "10:00",
      "arrival_date": "2024-11-12",
      "arrival_time": "11:30",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Business",
      "review": 4.4,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK366",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Karachi - Multan",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Multan International Airport",
      "departure_date": "2024-11-12",
      "departure_time": "15:00",
      "arrival_date": "2024-11-12",
      "arrival_time": "16:30",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Economy",
      "review": 4.3,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Multan International Airport",
        "return_arrival_airport": "Karachi Jinnah International Airport",
        "return_departure_date": "2024-11-15",
        "return_departure_time": "12:00",
        "return_arrival_date": "2024-11-15",
        "return_arrival_time": "13:30"
      }
    },
    {
      "flight_number": "PK367",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Lahore - Karachi",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": "2024-11-13",
      "departure_time": "08:00",
      "arrival_date": "2024-11-13",
      "arrival_time": "09:30",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK368",
      "airline": "Airblue",
      "image":"https://seeklogo.com/images/A/air-blue-logo-101E92F7B0-seeklogo.com.png",
      "from_to": "Karachi - Islamabad",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Islamabad International Airport",
      "departure_date": "2024-11-13",
      "departure_time": "12:00",
      "arrival_date": "2024-11-13",
      "arrival_time": "13:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.6,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Islamabad International Airport",
        "return_arrival_airport": "Karachi Jinnah International Airport",
        "return_departure_date": "2024-11-17",
        "return_departure_time": "9:00",
        "return_arrival_date": "2024-11-17",
        "return_arrival_time": "11:30"
      }
    },
    {
      "flight_number": "PK369",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Islamabad - Lahore",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Lahore Allama Iqbal International Airport",
      "departure_date": "2024-11-14",
      "departure_time": "10:00",
      "arrival_date": "2024-11-14",
      "arrival_time": "11:30",
      "flight_duration_hours": 1.5,
      "price": 8500,
      "ticket_class": "Business",
      "review": 4.1,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK370",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Karachi - Peshawar",
      "departure_airport": "Karachi Jinnah International Airport",
      "arrival_airport": "Peshawar International Airport",
      "departure_date": "2024-11-14",
      "departure_time": "15:00",
      "arrival_date": "2024-11-14",
      "arrival_time": "16:30",
      "flight_duration_hours": 1.5,
      "price": 9000,
      "ticket_class": "Economy",
      "review": 4.4,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Peshawar International Airport",
        "return_arrival_airport": "Karachi Jinnah International Airport",
        "return_departure_date": "2024-11-17",
        "return_departure_time": "2:00",
        "return_arrival_date": "2024-11-17",
        "return_arrival_time": "4:30"
      }
    },
    {
      "flight_number": "PK371",
      "airline": "Serene Air",
      "image":"https://cdn.brandfetch.io/idDF7AI81G/w/1310/h/302/theme/dark/logo.png?k=id64Mup7ac&t=1667655329160",
      "from_to": "Lahore - Karachi",
      "departure_airport": "Lahore Allama Iqbal International Airport",
      "arrival_airport": "Karachi Jinnah International Airport",
      "departure_date": "2024-11-15",
      "departure_time": "09:30",
      "arrival_date": "2024-11-15",
      "arrival_time": "11:00",
      "flight_duration_hours": 1.5,
      "price": 8000,
      "ticket_class": "Economy",
      "review": 4.3,
      "cheapest": true,
      "best": false,
      "quickest": false,
      "type": "one-way"
    },
    {
      "flight_number": "PK372",
      "airline": "Pakistan International Airlines",
      "image": "https://seeklogo.com/images/P/pia-pakistan-international-airlines-logo-256678A383-seeklogo.com.png",
      "from_to": "Islamabad - Multan",
      "departure_airport": "Islamabad International Airport",
      "arrival_airport": "Multan International Airport",
      "departure_date": "2024-11-15",
      "departure_time": "12:00",
      "arrival_date": "2024-11-15",
      "arrival_time": "13:30",
      "flight_duration_hours": 1.5,
      "price": 9500,
      "ticket_class": "Business",
      "review": 4.6,
      "cheapest": false,
      "best": true,
      "quickest": false,
      "type": "return",
      "return": {
        "return_departure_airport": "Multan International Airport",
        "return_arrival_airport": "Islamabad International Airport",
        "return_departure_date": "2024-11-20",
        "return_departure_time": "2:00",
        "return_arrival_date": "2024-11-20",
        "return_arrival_time": "4:30"
      }
    }

  ]


  export default flightDetails
  